services:
  # minio:
  #   restart: always
  #   image: quay.io/minio/minio
  #   environment:
  #     MINIO_ROOT_USER: ROOTNAME
  #     MINIO_ROOT_PASSWORD: CHANGEME123
  #   volumes:
  #     - ./datas/finance-tiledb:/data
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   command: server /data --console-address ":9001"

  # tdengine:
  #   restart: always
  #   image: tdengine/tdengine:3.0.3.0
  #   environment:
  #     TAOS_FQDN: tdengine
  #   volumes:
  #     - ./datas/tdengine:/var/lib/taos/
  #     - ./etc/tdengine:/etc/taos/
  #   ports:
  #     - 6030:6030
  #     - 6041:6041
  #     - 6043-6049:6043-6049
  #     - 6043-6049:6043-6049/udp

  # clickhouse:
  #   image: clickhouse/clickhouse-server
  #   restart: always
  #   ports:
  #     - 8123:8123 # for http API
  #     - 9000:9000 # for native client
  #   ulimits:
  #     nofile:
  #       soft: 262144
  #       hard: 262144
  #   volumes:
  #     # - ./datas/clickhouse:/var/lib/clickhouse/ # 不能映射，写入权限有BUG，见setup_clickhouse.ipynb
  #     - ./logs/clickhouse:/var/log/clickhouse-server/

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./datas/mongo:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/