services:
  minio:
    restart: always
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ~/WorkingDoc/tiledb:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
