CREATE DATABASE IF NOT EXISTS finance;
USE finance;
CREATE TABLE bars_daily (
    dt DateTime,
    name String,
    open Float32,
    high Float32,
    low Float32,
    close Float32,
    volume UInt32,
    amount UInt64,
    preclose Float32,
    net_profit_ttm Float32,
    cashflow_ttm Float32,
    equity Float32,
    asset Float32,
    debt Float32,
    debttoasset Float32,
    net_profit_q Float32,
    pe_ttm Float32,
    pb Float32,
    mkt_cap Float64,
    mkt_cap_ashare Float64,
    vip_buy_amt Float32,
    vip_sell_amt Float32,
    inst_buy_amt Float32,
    inst_sell_amt Float32,
    mid_buy_amt Float32,
    mid_sell_amt Float32,
    indi_buy_amt Float32,
    indi_sell_amt Float32,
    master_net_flow_in Float32,
    master2_net_flow_in Float32,
    vip_net_flow_in Float32,
    mid_net_flow_in Float32,
    inst_net_flow_in Float32,
    indi_net_flow_in Float32,
    total_sell_amt Float32,
    total_buy_amt Float32,
    net_flow_in Float32,
    turnover Float32,
    free_shares UInt64,
    total_shares UInt64,
    maxupordown Int8,
    maxupordown_at_open Int8,
    lb_up_count UInt8,
    lb_down_count UInt8
) ENGINE = MergeTree
PRIMARY KEY (dt);
INSERT INTO bars_daily FROM INFILE 'usr/000001.SZ.csv' FORMAT CSVWithNames;